// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID       string     `json:"id"`
	Title    string     `json:"title"`
	Products []*Product `json:"products"`
}

type NewCategory struct {
	Title string `json:"title"`
}

type NewProduct struct {
	Title      string `json:"title"`
	Price      int    `json:"price"`
	CategoryID string `json:"categoryId"`
}

type Product struct {
	ID       string    `json:"id"`
	Title    string    `json:"title"`
	Price    int       `json:"price"`
	Category *Category `json:"category"`
}
